version: '3.8'

networks:
  gtw-hsm-network:
    external: true
  btcgtw-network:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached

    command: sleep infinity

    networks:
      - btcgtw-network
      - gtw-hsm-network

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: bitcoin_gateway_db
    networks:
      - btcgtw-network

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    networks:
      - btcgtw-network

volumes:
  postgres-data:
